### ISSUE TITLE
Client side error

### ISSUE THREAD

**Issue by jugma** [mkalioby/django-mfa2#16]
I get the following error on Chrome debugger window when I try to add a security method.

DevTools failed to load SourceMap: Could not load content for http://localhost:8000/static/mfa/js/bootstrap-toggle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Please could you let me know if I am doing something wrong. Thank you.

Regards,
Jugma

**Comment by mkalioby** [comment]
That isn't a problem,  this is a map file for js, chrome is trying this on its own.
