### ISSUE TITLE
FIDO2

### ISSUE THREAD

**Issue by jugma** [mkalioby/django-mfa2#17]
When I try to setup the FIDO2 security method I get the following error on Chrome

Registeration Failed as Error on server, please try again later, try again or Go to Security Home

I don't see any errors on the server. I am using Chrome 84.0.4147.105 and Mac OS 10.15.5.

Please could you let me know what I may be doing wrong. Thank you.

Regards,
Jugma

**Comment by mkalioby** [comment]
That is tough to debug this way, but here points to check
- are you on HTTPS, 
- did you set the FIDO information properly in settings file,
- did you migrate the models properly,
- did you collect static

If you like you can send me a private repo to check.

**Comment by jugma** [comment]
I am actually trying out the example that comes in the repo.

**Comment by mkalioby** [comment]
Example needs HTTPS, which is not part of runserver so how did you satisfy that?

**Comment by jugma** [comment]
I fixed my HTTPS by using "python manage.py runsslserver". Now I am getting the below error
Registeration Failed as SecurityError: This is an invalid domain., try again or Go to Security Home

Thank you again for all your help.

**Comment by mkalioby** [comment]
Try to add port to FIDO_SERVER_ID or   Put Apache as frontend and use mod_proxy to forward to django

**Comment by jugma** [comment]
I put the port number to FIDO_SERVER_ID but I still get the same error

**Comment by mkalioby** [comment]
Can you try proxy over apache?

**Comment by jugma** [comment]
After fronting with ngnix I get the following error
Registeration Failed as SecurityError: The relying party ID is not a registrable domain suffix of, nor equal to the current domain

**Comment by mkalioby** [comment]
Can you send a screenshot of page and settings including FIDO Settings

**Comment by jugma** [comment]
Ok I got is working. I had to take off the port number in FIDO_SERVER_ID
