### ISSUE TITLE
QR Code not showing when trying to enable authenticator

### ISSUE THREAD

**Issue by mliedike** [mkalioby/django-mfa2#22]
When I goto /mfa and select the Authenticator App it returns the following

![Screen Shot 2020-09-08 at 9 51 12 PM](https://user-images.githubusercontent.com/6097797/92556125-ffee4480-f21d-11ea-92c9-6ac3fe942db8.png)

When I click on 'phone/PC' or 'enter this text' I see a Javascript error in the networking which states this:
Uncaught ReferenceError: showKey is not defined at HTMLAnchorElement.onclick ((index):158) onclick | @ | (index):158

Any idea how to get the QR code to render?  Also is there a way to disable the other MFA methods and only support the authenticator app?

**Comment by mkalioby** [comment]
Hello,

I think there is static resources which failed loading as the theme isn't right. Can you make sure that all STATIC Files are loaded by the browser, if error persist, can you share a link to the application.

For second question, you can use ```
MFA_UNALLOWED_METHODS
``` settings parameter

**Comment by mliedike** [comment]
Thank you for the quick response!  That was the issue, the static files were not being loaded properly.  I updated the my base.html file with block head and that resolved the issue.
