### ISSUE TITLE
Missing Migration

### ISSUE THREAD

**Issue by swainn** [mkalioby/django-mfa2#27]
I've recently updated to version 2.0.1 and I noticed that there was a migration that was not generated in my project. When I run manage.py makemigrations this is what it generates:

```
Migrations for 'mfa':
  ...\site-packages\mfa\migrations\0010_auto_20201106_1523.py
    - Alter field key_type on user_keys
```

Is django-mfa2 missing a migration?

**Comment by mkalioby** [comment]
What is the version of django are you using?and what is the database
backend?

**Comment by swainn** [comment]
Django 2.2 and PostgreSQL is the backend.

**Comment by mkalioby** [comment]
Thanks @swainn 
The issue has been solved in 049b174 and the version is bumped to 2.0.3.

I believe it will be easier to give me access to the conda, so I can release there as well.

**Comment by swainn** [comment]
Excellent. Thank you. I have opened a PR on the conda-forge feedstock to add you as a maintainer. Please comment on the PR "I agree to be a maintainer": https://github.com/conda-forge/django-mfa2-feedstock/pull/4

**Comment by swainn** [comment]
I have confirmed that this issue has been resolved in 2.0.3. Thank you.

**Comment by Moulde** [comment]
I know this is old and all, and really not trying to bash anyone, I just wanted to add that it's a bit frustrating when dependencies are changed in a patch release.
So one version has an issue, and the next release has a fix and a new requirement causing the release to not work for, in my case the django version.

**Comment by mkalioby** [comment]
Hello @Moulde 

Sorry for that.

Which version are you talking about?

**Comment by Moulde** [comment]
Ah sorry, I completely missed your reply. I was on django 1.11 but I don't remember which version of the django-mfa2 I was referring to, but it was a patch release which had a small fix, but also changed dependencies which then caused other issues, i believe it was no longer supporting the django version.
Which is totally fair, but I would not expect dependency changes in the same patch release as a bugfix.

Sorry about the long, and not very useful reply.
