### ISSUE TITLE
This project contains deprecated code (Django 2.0 deprecated render_to_response)

### ISSUE THREAD

**Issue by Lionqueen94** [mkalioby/django-mfa2#3]
Hi there,

Thanks for implementing this! However, in trying to get this working, we do face quite a few issues. First of all, the project contains deprecated code, namely calling the function render_to_response. See the Django docs, it has been deprecated in Django 2.0 and you state to support Django 2.1.
https://docs.djangoproject.com/en/2.2/topics/http/shortcuts/#render-to-response
Replacing the calls with render(request, template, optional context) works.

We are trying to get this working in Django 2.2, which might cause more problems, but this is the first big issue we faced.

Thanks in advance!

Regards,
Ellen

P.S. Is it possible to require either django-jsonfield or jsonfield? We are using django-jsonfield instead of jsonfield and using django-jsonfield for this app works fine. It would be nice to make django-jsonfield a possibility.

**Comment by mkalioby** [comment]
Hi Ellen,

Thanks for stopping by.

I replaced the render_to_reponse with render and added an example app to the repo, please test version 1.6.0 and let me know.
