### ISSUE TITLE
Help with integration with Allauth

### ISSUE THREAD

**Issue by ashrafZolkopli** [mkalioby/django-mfa2#46]
Hi  guys,

I'm not sure where would be the best place for communication, so here I am, 
Anyway I'm currently trying to integrate django-mf2 with my current application. 

In my current setup,  I am currently using django-allauth for all my authentication need.
Im honestly stuck with one part, which is go passwordless, 

![image](https://user-images.githubusercontent.com/59853680/119139746-f6d49900-ba75-11eb-9a60-c4f2d6904f60.png)

I get the logic to implement the get logic in my allauth login page, that is done.  My question is when do I set the cookies? 

for some context here is my Loginview code for allauth and MFA2

```python
from django.conf import settings
from django.shortcuts import render
from allauth.account.views import LoginView
from mfa.helpers import has_mfa
from allauth.exceptions import ImmediateHttpResponse
# Create your views here.


class MF2LoginView(LoginView):

    def get(self, request, *args, **kwargs):
        if getattr(settings, "MFA_QUICKLOGIN", False) and request.COOKIES.get('base_username'):
            username = request.COOKIES.get('base_username')
            res = has_mfa(username=username, request=request,)
            if res:
                return res
        return self.super().get(self, request, *args, **kwargs)

    def form_valid(self, form):
        success_url = self.get_success_url()
        res = has_mfa(self.request, username=form.user)
        if res:
            return res
        try:
            return form.login(self.request, redirect_url=success_url)
        except ImmediateHttpResponse as e:
            return e.response


MF2Login_View = MF2LoginView.as_view()
```

now that I think about it, what you need to do is to set the cookie once the user had been directed to my main page I guess?

**Comment by mkalioby** [comment]
Thanks for stopping by.

You can set the cookie anywhere, you can add it in the first login view or in the home page.

I don't know if it can go in log_user_in function, I can test that for you if you like.

**Comment by ashrafZolkopli** [comment]
hi, 

OMG I didn't think you would reply me this quickly, I was about to send a tweet. 

so basically from what I am able to gather is that, I just need a function that would check the session for MFA_Quicklogin, and cookies that have base_username 

I might suggest that we should hash the base_username portion first then we implement a reverse function hash to get the value of base_username due to security reason.

other then that I think this is such an amazing job you did

sincrely 
ashraf

**Comment by ashrafZolkopli** [comment]
Btw,

If you don't mind. Is it ok for me to make dev.to post about how to integrate MF2 with Allauth? 
I would definitely quote your work too.

I think an adapter or a way to integrate both would be great too

**Comment by mkalioby** [comment]
> hi, 
> 
> OMG I didn't think you would reply me this quickly, I was about to send a tweet. 
> 
> so basically from what I am able to gather is that, I just need a function that would check the session for MFA_Quicklogin, and cookies that have base_username 
> 
> I might suggest that we should hash the base_username portion first then we implement a reverse function hash to get the value of base_username due to security reason.
> 
> other then that I think this is such an amazing job you did
> 
> sincrely 
> ashraf

You don't need to hash as Django does this automatically through the SECRET_KEY

**Comment by mkalioby** [comment]
> Btw,
> 
> If you don't mind. Is it ok for me to make dev.to post about how to integrate MF2 with Allauth? 
> I would definitely quote your work too.
> 
> I think an adapter or a way to integrate both would be great too

Sure, be my guest, I'll be honoured.

Please close the issue.
