### ISSUE TITLE
NullBooleanField: Deprecation warning in Django 4.0

### ISSUE THREAD

**Issue by Sirneij** [mkalioby/django-mfa2#49]
This line https://github.com/mkalioby/django-mfa2/blob/ef8287666c02c43762da6779ea892ced583f01a5/mfa/models.py#L18 always throws a deprecation warning during migrations. It would be removed in Django 4.0. Please, let it be fixed in future release.

**Comment by mkalioby** [comment]
Closed in version 2.2
