### ISSUE TITLE
Passwordless approach

### ISSUE THREAD

**Issue by variable** [mkalioby/django-mfa2#58]
Hi just came across this package after been fiddling with [django-fido](https://github.com/CZ-NIC/django-fido) project, regarding the passwordless section in the README, it mentions about creating a cookie for the previously logged in `username`, I presume it's because we use that to know which user to perform the fido auth against?

Has anyone considered using combination of  using `resident_key` for discoverable credential from the key and storing the user handle against the credential in the django database?

Reference
https://github.com/CZ-NIC/django-fido/issues/137
https://github.com/CZ-NIC/django-fido/pull/139
https://github.com/CZ-NIC/django-fido/pull/142

**Comment by mkalioby** [comment]
Hello,

Thanks for stopping by.

You have a good point, but it depends on the FIDO2 library as it handles the communication, I can do some trials next week as I'm off this week and let you know
