### ISSUE TITLE
Add section on how to setup local dev enviroment

### ISSUE THREAD

**Issue by NADOOITChristophBa** [mkalioby/django-mfa2#64]
Hi there. 

Thanks for making this package.

I love yubikeys so much I am building a business around them.
I am currently working on building a closed network that only allows FIDO2 logins to get rid of passwords altogether. Django didn't like it when I tried to build a user model without passwords. So instead, I have randomly created ones that will never get used. I can do this because I provide yubikeys to all my customers/users free of charge, set up the whole account, and for out-of-network users will have Anonymous accounts that get sent an email to create a login session. 

I am still struggling with adding the package but what this is really about is that it would be nice if there were a section in the readme on how to set up the local dev environment to use https

You mention

> Note: U2F and FIDO2 can only be served under secure context (https)

in the readme. 

That is good to know but without mentioning how to do it or adding a link to how to set it up locally, working on this is rather difficult. It is not feasible for me to test in production. So I have been reading up on it but was not successful so far in setting it up. 

Do you happen to know where I can find this kind of information?

**Comment by Spitfireap** [comment]
Hi, it's true there isn't any information about it. Have you tried [this](https://timonweb.com/django/https-django-development-server-ssl-certificate/) ? :)

**Comment by mkalioby** [comment]
There are several ways to manage this:
- You can use [django-sslserver](https://pypi.org/project/django-sslserver/) and then use 'python manage.py runsslserver'
- Start Apache2 or nginx in front of runserver

**Comment by NADOOITChristophBa** [comment]
@Spitfireap Thank you I actually tried that one but was unsuccessful, or at least I still got the same message as below

@mkalioby Thank you as well. I installed ssslserver and did what it says to set up.
I still get this.
![image](https://user-images.githubusercontent.com/106314951/188267944-77793dc6-7cbe-4350-888b-c525c4bc5e96.png)
What I did notice, though, is that Chrome does not show "This is an untrustworthy site. Do you want to continue?" So something changed. Since I still don't get "the lock," as shown in the image, I assume SSL is still not active. 

I do not understand what the second option is supposed to mean. What are you trying to say by "in front"?

Thanks for the help!

**Comment by NADOOITChristophBa** [comment]
Ok I found the mistac I was making.

@Spitfireap The artical has a mistake and I didn't notice
See how here it says .pem
![image](https://user-images.githubusercontent.com/106314951/188270071-76ee89c3-5b86-4de1-9cfa-aebb449a5628.png) 
should be .cer
Same in the creation section.
Now it works!
So for anyone struggling with this do what is in the article linkedby @Spitfireap and make sure to replace the .pem with .cer during the mkcert step and the runserver_plus step.

I also Installed the .cer file as a trusted source and then using windows+r go into 
![image](https://user-images.githubusercontent.com/106314951/188270148-45f09e51-a8c0-446d-b776-f21641975369.png)
and install under your local user and PC Account.

I will make a short video and then add it to this post.

**Comment by mkalioby** [comment]
> @Spitfireap Thank you I actually tried that one but was unsuccessful, or at least I still got the same message as below
> 
> @mkalioby Thank you as well. I installed ssslserver and did what it says to set up.
> I still get this.
> ![image](https://user-images.githubusercontent.com/106314951/188267944-77793dc6-7cbe-4350-888b-c525c4bc5e96.png)
> What I did notice, though, is that Chrome does not show "This is an untrustworthy site. Do you want to continue?" So something changed. Since I still don't get "the lock," as shown in the image, I assume SSL is still not active. 

SSL is active but this indicates that the certificate isn't signed by a certificate authority and this makes sense as it is a self signed certificate.

> 
> I do not understand what the second option is supposed to mean. What are you trying to say by "in front"?

That means that Apache handles ssl in front of the django web server
> 
> Thanks for the help!
