### ISSUE TITLE
Looking for a package to implement passkeys (webauth) and have some security concerns

### ISSUE THREAD

**Issue by frjo** [mkalioby/django-mfa2#69]
1. Both "python-u2flib-server" and "fido2" packages are listed as requirements but it seems the later is a replacement for the first. The "python-u2flib-server" repo is archived. Are you planing to remove it?
2. The "ecdsa" package state that it should not be used in production, see https://pypi.org/project/ecdsa/#Security. Is it not a concern for "django-mfa2"?

**Comment by mkalioby** [comment]
Hello fryo,

- python-u2flib-server is required for U2F if you won't support U2F as 2FA, you can remove it.
- for ecdsa,  you can `pip install python-jose[pycryptodome]` to get rid of ecdsa as a requirement.

Also, for better support of PassKeys, you can test against [v3.0](https://github.com/mkalioby/django-mfa2/tree/v3.0) branch, which will give you more options

**Comment by frjo** [comment]
Thanks for quick answer! Will test it out.

**Comment by mkalioby** [comment]
Hello again @frjo 
I believe your use case is valid, especially now. as you don't need this package just for passkeys. For that, I started a new project [django-passkeys](https://github.com/mkalioby/django-passkeys) which shall be simpler and easier to implement. 
Please give it a try and let me know there if you face any issues.
