### ISSUE TITLE
Commented out import in views.py

### ISSUE THREAD

**Issue by d3cline** [mkalioby/django-mfa2#8]
When I go to delete an object I see a 500 which complains that HttpResponse is missing. The imports show it was there and is now removed, why is that?
```
#from django.http import HttpResponse,HttpResponseRedirect
...
from django.http import HttpResponseRedirect
```
Changing which is commented out manually fixes this. Can it be fixed and pushed to pip?

**Comment by mkalioby** [comment]
Sure, you can make it as PR so you become a contributor.

**Comment by d3cline** [comment]
[posted](https://github.com/mkalioby/django-mfa2/pull/9) ty

**Comment by mkalioby** [comment]
Merged, Released to GitHub and PyPi
Thank you
