### ISSUE TITLE
Issue with 'collectstatic' in Django 4.2+ and django-mfa2 2.8.0

### ISSUE THREAD

**Issue by camposmoreira** [mkalioby/django-mfa2#80]
I encountered an issue when running `python manage.py collectstatic` in a Django project with the following configuration:

- Django: 4.2.7
- django-mfa2: 2.8.0
- Staticfiles storage: "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

**Error Message:**
```
ValueError: The file 'mfa/js/qrious.min.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fa5f2e5e770>.
```

**Context:**
Upon investigation, it seems that the issue is related to changes introduced in Django 4.2, where `ManifestStaticFilesStorage` now replaces paths to JavaScript source map references with their hashed counterparts. The relevant changelog can be found [here](https://docs.djangoproject.com/en/5.0/releases/4.0/).

**Observation:**
The files `mfa/static/mfa/js/bootstrap-toggle.min.js` and `mfa/static/mfa/js/qrious.min.js` are referencing source map files as follows:

```javascript
//# sourceMappingURL=bootstrap-toggle.min.js.map
//# sourceMappingURL=qrious.min.js.map
```

**Proposal for Solution:**
To resolve this issue, I propose adding the missing `.map` files. The required files can be found at the following locations:

- [bootstrap-toggle.min.js.map](https://github.com/minhur/bootstrap-toggle/blob/master/js/bootstrap-toggle.min.js.map)
- [qrious.min.js.map](https://github.com/neocotic/qrious/blob/master/dist/qrious.min.js.map)

By including these map files in the project, the `collectstatic` process should complete successfully.

Please let me know if you need any further information or clarification.

**Comment by mkalioby** [comment]
Create catch. Can you open a PR with this updates?

Welcome to contributors.

**Comment by camposmoreira** [comment]
Opened a PR (https://github.com/mkalioby/django-mfa2/pull/81) with the changes
