### ISSUE TITLE
Can not register Biometric Authentication in Firefox

### ISSUE THREAD

**Issue by hatamiarash7** [mkalioby/django-mfa2#86]
Hi!

I can't register a new Biometric Authentication in Firefox. Google Chrome and Safari are OK... Just Firefox. I have this error:

<img width="719" alt="image" src="https://github.com/mkalioby/django-mfa2/assets/16325641/afb474e4-f1b4-4451-8842-928b8dc246ab">

This problem exists for registration only, the login process is working.

MacOS 14.2.1
Firefox 121.0.1

**Comment by mkalioby** [comment]
Hello,
What is your authentication backend? the userid is the username ascii encoded, you can check the value received from backend in the console, so please share it

**Comment by hatamiarash7** [comment]
@mkalioby I think the response and user.id value is correct:

<img width="525" alt="image" src="https://github.com/mkalioby/django-mfa2/assets/16325641/10631918-65d6-46cc-8a59-89259062c95e">

I checked the response value in different browsers and it was the same

**Comment by mkalioby** [comment]
I'll try here and let you know

**Comment by hatamiarash7** [comment]
Ok ... I find the problem. The example project is good. I think there is a little problem with the `Bitwarden` extension in Firefox. This plugin supports FIDO2.

I'll log the output of `navigator.credentials.create(options)` and see that there are some `@moz-extension` errors in the stack:

<img width="563" alt="image" src="https://github.com/mkalioby/django-mfa2/assets/16325641/098c0851-9cbe-4738-a687-e7aedecabf4f">

Of course, I tested the use of this extension for login and there was no problem. It also worked correctly on the [django-passkeys](https://github.com/mkalioby/django-passkeys) project.

Now I don't know if the problem is with your code or this extension.

**Comment by mkalioby** [comment]
Try a longer/shorter username and see if it will work

**Comment by hatamiarash7** [comment]
No, it's now work. There is a problem with Passkey extensions like Bitwarden.
