### ISSUE TITLE
Is it possible to log in without Bluetooth?

### ISSUE THREAD

**Issue by hellgadev** [mkalioby/django-mfa2#88]
The lack of Bluetooth on devices can cause an authorization problem if webAuthn is the only authorization method. Is it possible to configure so that authorization does not require Bluetooth?

**Comment by mkalioby** [comment]
Use security keys or platform authenticators like Windows Hello or TouchID on Mac OSX, but the only way for key to jump from an ecosystem to another e.g from Apple/Android to MS Windows is Bluetooth over BLE

**Comment by mkalioby** [comment]
If you still need help reopen the issue.
